config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get '/products.json', to: 'products#json', as: 'json'

  get '/products/:id/buy', to: 'products#buy', as: 'purchase'
  get '/cart', to: 'products#cart', as: 'cart'
  get '/checkout', to: 'products#checkout', as: 'checkout'

  get '/clearsession', to: 'application#clearsession', as: 'clearsession'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  resources :products, path: '/products'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
    validates :name, presence: true
    validates :price, comparison: {greater_than: 0}
    validates :stock, comparison: {greater_than_or_equal_to: 0}
    has_one_attached :image # method found at https://tinyurl.com/4mpvx49d
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :initialize_session
    
    def clearsession
        session[:user] = nil
        session[:cart] = nil
        redirect_to root_path
    end

private
    def initialize_session
        empty_cart = Product.all.map{|p| [p.id, 0]}.to_h # maps product id and count in session
        session[:cart] ||= empty_cart # creates an empty cart if one does not exist
        session[:user] ||= nil # creates an empty user if one does not exist
        @item_count = session[:cart].values.reduce(:+) # number of products in cart
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :initialize_session

    def index
        @products = Product.all
    end

    def show
        @product = Product.find(params[:id])
    end

    def new
        if !helpers.super_user? 
            redirect_to login_path 
        else
            @product = Product.new
        end
    end

    def create
        @product = Product.new(product_params)

        if @product.save
            redirect_to @product
        else
            render :new, status: :unprocessable_entity
        end
    end
    
    def edit
        if !helpers.super_user? 
            redirect_to product_path
        else
            @product = Product.find(params[:id])
        end
    end
    
    def update
        @product = Product.find(params[:id])

        if @product.update(product_params)
            redirect_to product_path
        else
            render :edit, status: :unprocessable_entity
        end
    end
    
    def destroy
        if !helpers.super_user? 
            redirect_to product_path
        else
            @product = Product.find(params[:id])
            @product.destroy
        
            redirect_to products_path, status: :see_other
        end
    end

    def cart
        @cart = session[:cart]
            .filter{|id,count| count>0} # only takes products with > zero counts
            .map{|id,count| [Product.find(id),count]} # associates session to dbase
    end

    def checkout
        session[:cart] = nil # empties cart after perchases
        redirect_to products_path
    end
    
    def buy
        @product = Product.find(params[:id])
        @product.stock = @product.stock-=1
        if @product.stock < 0
            redirect_to product_path
        else
            @product.save
            curr_q = session[:cart][@product.id.to_s].to_i
            curr_q += 1
            session[:cart][@product.id.to_s]=curr_q
            redirect_to product_path
        end
    end

    def json
        @products = Product.all
        render json: @products, only: [:id, :name, :price, :stock]
    end
    
private
    def product_params
        params.require(:product).permit(:name, :description, :stock, :price, :status, :image)
    end
    def initialize_session
        empty_cart = Product.all.map{|p| [p.id, 0]}.to_h # maps product id and count in session
        session[:cart] ||= empty_cart # creates an empty cart if one does not exist
        session[:user] ||= nil # creates an empty user if one does not exist
        @item_count = session[:cart].values.reduce(:+) # number of products in cart
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login
    @users = User.all
  end

  def create
    @user = User.find_by(name: params[:name])
    if @user.present? && (@user.password == params[:password])
      session[:user] = @user.id
      redirect_to root_path
    else
      message = "Something went wrong! Check your username and password."
      redirect_to login_path, notice: message
    end
  end

  def destroy
    session[:user] = nil
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :initialize_session
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    if helpers.super_user? || helpers.user_match?
      @user = User.find(params[:id])
      @user.destroy
      
      redirect_to login_path, status: :see_other
    else
      message = "You can't do that."
      redirect_to login_path, notice: message
    end
  end 

  def edit
    if helpers.super_user? || helpers.user_match?
      @user = User.find(params[:id])
    else
      message = "Something went wrong! This is not you!"
      redirect_to login_path, notice: message
    end
  end

  def update
    if helpers.super_user? || helpers.user_match?
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to @user
      else
        render :edit, status: :unprocessable_entity
      end
    else
      message = "Something went wrong! This is not you!"
      redirect_to login_path, notice: message
    end
  end

  def show
    @user = User.find(params[:id])
    
    if helpers.user_match?
      @viewer = "Owner"
    else
      @viewer = @user.name.to_s
    end
  end

private
    def user_params
      params.require(:user).permit(:name, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def logged_in?
        !!session[:user]
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user]) if !!session[:user]
    end
    
    def super_user?
        session[:user].to_s == "1" || session[:user].to_s == "2"
    end

    def user_match?
        session[:user].to_s == params[:id].to_s
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_mynavbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Erots|storE", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <a href="/list" class="nav-link active">Products</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Hello | What can we do for you?</h1>
            <br>
        </div>
    </div>
    <div class="row">
        <div class="col"><h5>
            <%if logged_in? %>Logged in as | <%=current_user.name%> | <%= link_to "Logout", logout_path, class:"btn-sm btn-dark"%>
            <%else%>You are not logged in | <%= link_to "Login", login_path, class:"btn-sm btn-dark"%> || <%= link_to "Create Login", new_user_path, class:"btn-sm btn-dark", disabled: true %><%end%>
        </h5></div>
        <div class="col"><h5>
            <%= @products.count %> | Products and counting
        </h5></div>
    </div>
    <div class="row">
        <h2><br><strong>FAQ's</strong></h2>
        <div class="col">
            <h3>What do we sell?</h3>
            <br>
            <p>Absolutely nothing, this website is entirely for show so dont expect anything to actualy come to you. However, if you want to give me you credit card info, I'll take it</p>
        </div>
        <div class="col">
            <h3>Where did we come from?</h3>
            <br>
            <p>Blood, sweat, tears, and pounds upon pounds of caffine. This website is the product of the a college project to learn the Ruby on Rails system.</p>
        </div>
        <div class="col">
            <h3>Who are we?</h3>
            <br>
            <p>A bunch of broke college students. Well one specifically, but that's a story for another time.</p>
        </div>
    </div>
    
</div>

app/views/home/products.html.erb
<%= render "mynavbar", home: @home %>

<div class="container">
    <div class="row">
        <div class="col">
            <h1>Products|Treat yourself</h1>
        </div>
    </div>
</div>

app/views/layouts/_mynavbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Erots|storE", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Products", products_path, class: "nav-link active" %>
        </li>
        <%uid = session[:user].to_s%>
        <%if super_user? %> <!--ONLY DISPLAYED TO SUPER USERS -->
        <li class="nav-item">
          <%= link_to "New Product", new_product_path, class: "nav-link active" %>
        </li>  
        <li class="nav-item">
          <%= link_to "Create Login", new_user_path, class:"nav-link active"%>
        </li>
        <%end%>
        <li class="nav-item">
          <%= link_to "Cart | #{@item_count}", cart_path, class: "nav-link active" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Erots</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/mynavbar" %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <div class="container">
    <div class="row">
      <div class="col mb-3"> <%# Product Name %>
        <%= form.text_field :name, :placeholder => "Product Name", class: "form-control" %>
      </div>
    </div> 
    <div class="row">
      <div class="col mb-3"> <%# Product Description%>
            <%= form.text_area :description, :placeholder => "Product Description", class: "form-control" %>          
      </div>
    </div>
    <div class="row">
      <div class="col mb-3"> <%# Product Stock %>
            <%= form.number_field :stock, :placeholder => "Stock", class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col mb-3"> <%# Product Price %>
        <%= form.number_field :price, step: 0.01, :placeholder => "Price", class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col mb-3"> <%# Product Image%>
        <br>
        <p>Product Image</p>
        <%= form.file_field :image, :placeholder => "Product Image", class: "form-control" %>
        <br>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <h5><%= form.submit class: 'btn-dark btn-sm'%></h5>
      </div>
      <div class="col">
        <h5><strong><%= form.label :status %> | </strong>
        <%= form.select  :status, ['public', 'private', 'archived'], selected: 'public', class: "form-select form-select-sm" %></h5>
      </div>
    </div>
  </div>
<% end %>

app/views/products/cart.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Cart | You can have it all</h1>
        </div>
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-4">
    <ul>
      <%sum = 0%>
      <% @cart.each do |product, count| %>
        <div class="col">
          <li><%="#{product["name"]} | $#{product["price"]} x #{count}"%></li>
          <%sum += product["price"] * count%>
        </div>
      <% end %>
    </ul>
    </div>
    <div class="row">
      <div class="col">
        <%="Your total is | $#{sum} "%><button class="btn-dark btn-sm" type="button"><%= link_to "Checkout", checkout_path%></button>
      </div>
    </div>
</div>

app/views/products/edit.html.erb
<div class="container"> 
  <div class="row">
    <div class="col">
      <h1>Edit Product</h1>
    </div>
  </div>
</div>
<%= render "form", product: @product %>

app/views/products/index.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Products | Treat yourself</h1>
        </div>
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-4">
      <% @products.each do |product| %>
        <div class="col">
          <div class="card">
            <% if product.image.attached? %>
              <%= image_tag(product.image, class: "card-img-top", style: "width: 353px; height: 234px; object-fit: cover;") %>
            <% end %>
            <div class="card-body">
            <div class="row">
              <div class="col-9">
                <h5 class="card-title"><strong>
                  <% if product.stock <= 0 %>
                    <%= link_to "#{product.name} | Out of Stock ", product_path(product), class: "title" %>
                  <% else %>
                    <%= link_to "#{product.name} | $#{product.price} ", product_path(product), class: "title" %>
                  <% end %></p>
                </strong></h5>
              </div>
              <div class="col" style="text-align: right">
                <button class="btn-dark btn-sm" type="button"><%= link_to "Buy", "/products/#{product.id}/buy"%></button>
              </div>
              </div>
              <p class="card-text"><%= truncate(product.description,length:100,separator:' ') %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row">
        <div class="col">
            <br>    
        </div>
    </div>
</div>

app/views/products/list.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Products | Treat yourself</h1>
        </div>
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-4">
      <% @products.each do |product| %>
        <div class="col">
          <div class="card">
            <% if product.image.attached? %>
              <%= image_tag(product.image, class: "card-img-top") %>
            <% end %>
            <div class="card-body">
              <h5 class="card-title"><strong><%= link_to product.name, product, class: "title" %> | $<%= product.price %></strong></h5>
              <p class="card-text"><%= sanitize(product.description[0,100]) %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row">
        <div class="col">
            <br>    
        </div>
    </div>
</div>

app/views/products/new.html.erb
<div class="container"> 
  <div class="row">
    <div class="col">
      <h1>New Product</h1>
    </div>
  </div>
</div>

<%= render "form", product: @product %>

app/views/products/show.html.erb
<div class="container"> 
  <div class="row">
    <div class="col">
      <h1><%= @product.name %></h1>
      <p><strong>Description | </strong><%= @product.description %></p>
      <p><strong>Price | </strong><%= @product.price %></p>
      <p><strong>Stock | </strong>
      <% if @product.stock <= 0 %>
        Out of Stock
      <% else %>
        <%= @product.stock %>
      <% end %></p>
      <button class="btn-dark btn-sm" type="button"><%= link_to "Buy", purchase_path(@product) %></button>
      <button class="btn-dark btn-sm" type="button"><%= link_to "Edit", edit_product_path(@product)%></button>
      <button class="btn-dark btn-sm" type="button"><%= link_to "Destroy", product_path(@product), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li></button>
    </div>
    <div class="col">
      <br>
      <% if @product.image.attached? %>
        <%= image_tag(@product.image, width: 100, class: "scaling_img") %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with model: @user do |form|%>
  <div class="container">
    <div class="row">
      <div class="col mb-3"> <%# User Name %>
        <%= form.text_field :name, :placeholder => "Username", class: "form-control" %>
      </div>
    </div> 
    <div class="row">
      <div class="col mb-3"> <%# Password %>
            <%= form.text_field :password, :placeholder => "Password", class: "form-control" %>          
      </div>
    </div>
    
    <div class="row">
      <div class="d-grid gap-2">
        <%= form.submit @submit_text, class: 'btn btn-dark'%>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container"> 
  <div class="row">
    <div class="col">
      <h1>Users | Edit Account</h1>
    </div>
  </div>
</div>
<%@submit_text = "Update Information"%>
<%= render "form", user: @user %>

app/views/users/new.html.erb
<div class="container"> 
  <div class="row">
    <div class="col">
      <h1>Users | Create Account</h1>
    </div>
  </div>
</div>
<%@submit_text = "Create User"%>
<%= render "form", product: @product %>

app/views/users/show.html.erb
<div class="container"> 
  <div class="row">
    <div class="col">
      <h1>Users | View Account</h1><br>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <p><strong>Username | </strong><%= @user.name %></p>
    </div>
    <div class="col">
      <p><strong>Viewer | </strong><%= current_user.name %></p>
    </div>
  </div>
</div>